/**
 * The red-team local-agent callback contract.
 *
 * Unlike `src/simulation/task.ts`'s `BaseTask` abstract class, the red-team
 * handler is a **plain function** — no class, no `instanceof` gate. This is
 * an intentional divergence chosen to keep the developer's code short — no
 * class to extend. The signature also carries a
 * `turnIndex` (simulation's `BaseTask.run` has no turn number).
 */

/**
 * The developer's local agent response. Either a plain string message, or a
 * richer result carrying an explicit session id override.
 */
export type RedteamAgentResponse = string | RedteamTaskResult;

/**
 * Richer handler return shape, when the developer needs to report a
 * different/derived session id alongside the message.
 */
export interface RedteamTaskResult {
  message: string;
  sessionId?: string;
}

/**
 * The developer-authored local agent callback.
 *
 * @param prompt - The prompt/attack text generated by the red-team for this turn.
 * @param sessionId - The session identifier this turn belongs to.
 * @param turnIndex - The zero-based index of this turn within the session.
 * @returns The agent's response — a plain string, or a `{message, sessionId}`
 *          object — synchronously or as a Promise.
 */
export type RedteamAgentHandler = (
  prompt: string,
  sessionId: string,
  turnIndex: number,
) => Promise<RedteamAgentResponse> | RedteamAgentResponse;

/**
 * Invoke the developer's handler and normalize its return value.
 *
 * Tolerates both sync and async handlers (awaiting a non-Promise value is a
 * no-op). The *return value* is still duck-typed, mirroring
 * `src/simulation/utils.ts:executeTask` — a plain string, or an object with a
 * string `message` (and optional `sessionId`). Any other shape throws.
 *
 * @param handler - The developer's local agent callback.
 * @param prompt - The prompt to pass as the handler's first argument.
 * @param sessionId - The session id to pass as the handler's second argument.
 * @param turnIndex - The turn index to pass as the handler's third argument.
 * @returns `{ output, sessionId? }` extracted from the handler's return value.
 * @throws Error if the handler's resolved return value is not a string or a
 *         `{message: string}`-shaped object.
 */
export async function executeHandler(
  handler: RedteamAgentHandler,
  prompt: string,
  sessionId: string,
  turnIndex: number,
): Promise<{ output: string; sessionId?: string }> {
  const result = await handler(prompt, sessionId, turnIndex);

  if (typeof result === "string") {
    return { output: result };
  }

  if (
    result &&
    typeof result === "object" &&
    typeof (result as RedteamTaskResult).message === "string"
  ) {
    const r = result as RedteamTaskResult;
    return { output: r.message, sessionId: r.sessionId };
  }

  throw new Error(
    `redteam handler must return string | { message: string }, got ${typeof result}`,
  );
}
